spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;  # 인메모리 DB로 변경
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true  # 개발 환경에서만 활성화
      path: /h2-console
      settings:
        web-allow-others: false  # 원격 접속 차단
  sql:
    init:
      mode: always  # 서버 실행 시 SQL 스크립트 실행
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

# 서버 설정 추가
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# 로깅 설정 추가
logging:
  level:
    com.example.carcheckupback: DEBUG
    org.mybatis: DEBUG
