spring:
  datasource:
    url: jdbc:h2:/Users/maebbubi/test;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE  # 인메모리 DB
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true  # H2 콘솔 활성화
      path: /h2-console
  sql:
    init:
      mode: always  # 서버 실행 시 SQL 스크립트 실행
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
