CREATE TABLE IF NOT EXISTS CARS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    make VARCHAR(100),
    model VARCHAR(100),
    car_year INT,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS MANUFACTURERS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    country VARCHAR(100),
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 기존 CARS 테이블에 manufacturer_id 컬럼 추가하여 관계 설정 (선택사항)
ALTER TABLE CARS ADD COLUMN IF NOT EXISTS manufacturer_id BIGINT;
ALTER TABLE CARS ADD CONSTRAINT IF NOT EXISTS fk_manufacturer FOREIGN KEY (manufacturer_id) REFERENCES MANUFACTURERS(id);
